// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQuC3Jg5f0ZKntgabMsVJ70FzfJWoNAy4',
    appId: '1:72339378706:web:768c65f1319d37c0bebecb',
    messagingSenderId: '72339378706',
    projectId: 'auth-4ee25',
    authDomain: 'auth-4ee25.firebaseapp.com',
    storageBucket: 'auth-4ee25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFuhE9dJWY75bZsoCogf_PDQ9HxQS9fh8',
    appId: '1:72339378706:android:df6963b5872c109ebebecb',
    messagingSenderId: '72339378706',
    projectId: 'auth-4ee25',
    storageBucket: 'auth-4ee25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpElZibjg7pZen0cK5q-pBNbCBGOWjppM',
    appId: '1:72339378706:ios:c7f0dfd10b072158bebecb',
    messagingSenderId: '72339378706',
    projectId: 'auth-4ee25',
    storageBucket: 'auth-4ee25.appspot.com',
    iosClientId: '72339378706-vmt53tomi2l887tdv5udo7ncklkiarhn.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpElZibjg7pZen0cK5q-pBNbCBGOWjppM',
    appId: '1:72339378706:ios:c02abe121ac5c052bebecb',
    messagingSenderId: '72339378706',
    projectId: 'auth-4ee25',
    storageBucket: 'auth-4ee25.appspot.com',
    iosClientId: '72339378706-g2qdu219jkhbia8nsgc00foa4nens2or.apps.googleusercontent.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
